name: update-readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Debug environment
        env:
          GITHUB_TOKEN: ${{ secrets.LANGUAGES }}
          GITHUB_USER: ${{ github.repository_owner }}
        run: |
          echo "Repository owner: $GITHUB_USER"

          if [ -z "$GITHUB_TOKEN" ]; then
            echo "❌ GITHUB_TOKEN is EMPTY"
            exit 1
          fi

          echo "✅ Token exists"
          echo "Token length: ${#GITHUB_TOKEN}"

      - name: Run language stats script
        env:
          GITHUB_TOKEN: ${{ secrets.LANGUAGES }}
          GITHUB_USER: ${{ github.repository_owner }}
        run: python .github/scripts/update_readme.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md

          git diff --staged --quiet || git commit -m "chore: update language stats"

          git push
